254-RN-Login-page
connacx2020/cx-devx-learn-rn pull request #1
Opened 2020-05-07 05:04 UTC by Horizon19911

2020-05-07 05:20 UTC, Horizon19911 commented
@oaksoe @minkhant285

2020-05-07 05:21 UTC, minkhant285 requested changes
@Horizon19911  I have some PR comments for you.

2020-05-07 05:21 UTC, minkhant285 commented on src/components/Login/login.tsx
> +                {(FormikProps) => {
@Horizon19911 (FormikProps) to (FormikProps:any)

2020-05-07 05:21 UTC, minkhant285 commented on src/components/Login/login.tsx
> +                onSubmit={(values) => {
change values to  values: FormValues

2020-05-07 05:21 UTC, minkhant285 commented on src/components/Home/home.tsx
> +const styles = StyleSheet.create({
@Horizon19911  seperate style file and component file

2020-05-07 05:21 UTC, minkhant285 commented on src/components/Login/login.tsx
> +import {compose} from 'recompose';
make format {style} to { style } and change other similar code

2020-05-10 04:15 UTC, minkhant285 approved these changes

2020-05-10 04:16 UTC, merged