features/297-Course-detail-page
connacx2020/cx-devx-learn-rn pull request #7
Opened 2020-05-27 11:29 UTC by Horizon19911

Thank You Bro!

2020-05-27 11:29 UTC, Horizon19911 commented
@minkhant285

2020-05-31 05:43 UTC, minkhant285 requested changes

2020-05-31 05:43 UTC, minkhant285 commented on src/components/CourseDetail/index.tsx
> +    },[1]);
why 1

2020-05-31 05:43 UTC, minkhant285 commented on src/components/CourseSection/index.tsx
> +import React from 'react';
change index.tsx to courseSection.tsx don't use index.tsx

2020-05-31 05:43 UTC, minkhant285 commented on src/Routes/index.tsx
> +            {false ? <AuthStack /> : <AppDrawer />}
why false

2020-05-31 05:45 UTC, Horizon19911 commented on src/components/CourseDetail/index.tsx
> +    },[1]);
use to hide the bottom tab

2020-06-02 03:58 UTC, merged